export { default as request } from './components/request';
export { default as Alter } from './components/Alter'
export { default as Avatar } from './components/Avatar'
export { default as Bar } from './components/Bar'
export { default as Banner } from './components/Banner'
export { default as Breadcrumb } from './components/Breadcrumb'
export { default as Button } from './components/Button'
export { default as Card } from './components/Card'
export { default as CodeEditor } from './components/CodeEditor'
export { default as Empty } from './components/Empty'
export { default as Image } from './components/Image'
export { default as Indicator } from './components/Indicator'
export { default as Label } from './components/Label'
export { default as List } from './components/List'
export { default as Markdown } from './components/Markdown'
export { default as Modal } from './components/Modal'
export { default as Nav } from './components/Nav'
// export { default as Notify } from './components/Notify'
// export { default as NotifyManager } from './components/NotifyManager'
export { default as Panel } from './components/Panel'
export { default as ScrollLoad } from './components/ScrollLoad'
export { default as Status } from './components/Status'
// export { default as Steps } from './components/Steps'
export { default as Switch } from './components/Switch'
export { default as Tag } from './components/Tag'
export { default as Text } from './components/Text'
// export { default as TypeSelect } from './components/TypeSelect'
// export { default as Upload } from './components/Upload'

export { getLocalStorage, setLocalStorage, removeLocalStorage } from './utils/storage';
export { RE } from './utils/commonRE';